### ISSUE TITLE
"CLI has stopped working" when launching user guide example

### ISSUE THREAD

**Issue by Doggie52** [amphp/thread#13]
OS: Windows 8.1 x64
PHP: 5.6.3 (cli) (TS VC11)
Libs:

``` json
"amphp/amp": "0.15.0",
"amphp/thread": "dev-master"
```

I'm running the following code

``` php
include('vendor/autoload.php');

function myMultiply($x, $y) {
    return $x * $y;
}

(new Amp\NativeReactor)->run(function($reactor) {
    try {
        $dispatcher = new Amp\Thread\Dispatcher($reactor);
        var_dump(yield $dispatcher->call('myMultiply', 6, 7));
    } catch (Exception $e) {
        printf("Something went terribly wrong: %s\n", $e->getMessage());
    } finally {
        $reactor->stop();
    }
});
```

taken straight from the user guide. I am running a bog standard PHP with a very minimal `php.ini` file.

When executing this with `php test.php`, the CLI immediately crashes with a standard Windows message "CLI has stopped working". What's going on? What can I do to debug this?

**Comment by kelunik** [comment]
We have stable releases now, please use `amphp/parallel` instead.
