### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by 2byte** [amphp/thread#14]
Hi, such problem, all example execute errors.

```
function slowAddition($x, $y) {
            sleep(1);
            return $x + $y;
        }

        try {
            $dispatcher = new Dispatcher;

            $a = $dispatcher->call('slowAddition', 1, 5);
            $b = $dispatcher->call('slowAddition', 10, 10);
            $c = $dispatcher->call('slowAddition', 11, 31);

            // Combine these three promises into a single promise that
            // resolves when all of the individual operations complete
            $comboPromise = Amp\all([$a, $b, $c]);

            // Our three calls will complete in one second instead of
            // three because they all run at the same time
            list($a, $b, $c) = $comboPromise->wait();
            var_dump($a, $b, $c);

            /*
            int(6)
            int(20)
            int(42)
            */

        } catch (\Exception $e) {
            printf("Something went wrong:\n\n%s\n", $e->getMessage());
        }
```

return 
Something went wrong:
This function is deprecated and scheduled for removal. Please use Amp\getReactor()

next

```
function myMultiply($x, $y) {
            return $x * $y;
        }

        (new Amp\NativeReactor)->run(function($reactor) {
            try {
                $dispatcher = new Dispatcher($reactor);
                var_dump(yield $dispatcher->call('myMultiply', 6, 7));
            } catch (\Exception $e) {
                printf("Something went terribly wrong: %s\n", $e->getMessage());
            } finally {
                $reactor->stop();
            }
        });
```
## [Fri Jul  3 17:35:55 2015]  Script:  '-'

/home/ess2/php5/php-5.6.9/Zend/zend_variables.c(46) : Block 0x099b16ac status:
## [Fri Jul  3 17:35:55 2015]  Script:  '-'

/home/ess2/php5/php-5.6.9/Zend/zend_variables.c(188) : Block 0x099b1668 status:
/home/ess2/php5/php-5.6.9/Zend/zend_execute.h(80) : Actual location (location was relayed)
## [Fri Jul  3 17:35:55 2015]  Script:  '-'

/home/ess2/php5/php-5.6.9/Zend/zend_hash.c(553) : Block 0x099b1958 status:
## [Fri Jul  3 17:35:55 2015]  Script:  '-'

/home/ess2/php5/php-5.6.9/Zend/zend_hash.c(556) : Block 0x094e4cd8 status:
## [Fri Jul  3 17:35:55 2015]  Script:  '-'

/home/ess2/php5/php-5.6.9/Zend/zend_variables.c(46) : Block 0x099afedc status:
## [Fri Jul  3 17:35:55 2015]  Script:  '-'

/home/ess2/php5/php-5.6.9/Zend/zend_variables.c(188) : Block 0x099afae0 status:
/home/ess2/php5/php-5.6.9/Zend/zend_execute.h(80) : Actual location (location was relayed)
Invalid pointer: ((thread_id=0xB69BD700) != (expected=0xB635FB40))

etc...

**Comment by metamaker** [comment]
Same here. Feels like this project is dead.

**Comment by bwoebi** [comment]
The project is indeed dead … it'll be update in near future to be also working with Amp/v2 (which is being worked out right now)

**Comment by Trexology** [comment]
Any alternative to this package?

**Comment by metamaker** [comment]
I fulfilled my needs by using RabbitMQ/Gearman for multi-threading in PHP instead of AMP/pthreads/etc. It uses a bit different approach to multi-threading, i.e. the intermediate queue for messaging between workers/clients, but works pretty fast, reliable and with small overhead. Maybe it will be useful for you too, though I hope that community will release AMP/v2. The more alternatives is the better.

**Comment by trowski** [comment]
There is now an alternative that supersedes this package: [amphp/parallel](https://github.com/amphp/parallel). The package is only compatible with Amp v2 (unreleased, but is the *master* branch of [amphp/amp](https://github.com/amphp/amp) and the *amp_v2* branch of other packages).

**Comment by Trexology** [comment]
Thanks guys, lucky to find that the community is still active for this project.

I am using Laravel 5.2 with pthread (php5.5) to execute multiple process concurrently and combine ALL the end result. But i bump into some issue when calling method from php classes

I have attached an extract of my code:

`class SearchCar extends \Thread
{
    public function __construct($company, $filter, $stations)
    {
        $this->company = $company;
        $this->filter = $filter;
        $this->stations = $stations;
    }

    public function run()
    {
        require_once __DIR__.'/../../../../bootstrap/autoload.php';
        $app = require_once __DIR__.'/../../../../bootstrap/app.php';

        $api = new AdaptorSelector($this->company); // <-- nothing happen beyond this line
        echo $api->adaptor->name;
        $this->html = $api->adaptor->searchAllStationsCars($this->filter,$this->stations);

        // $this->html = $api->adaptor->name;
    }
}
`


`$searches = ['honda', 'toyota', 'hyundai'];
    foreach ($searches as &$search) {
        $search = new SearchCar($search, $filter, $stations);
        $search->start(PTHREADS_INHERIT_NONE);
    }

    foreach ($searches as $search) {
        $search->join();
        echo $search->html."\n";}
`


Not even sure is it due to the way laravel bootstrap the app or something else... I know my question is kinda vague, hope someone can shed some light.

**Comment by kelunik** [comment]
We have stable releases now, please use `amphp/parallel` instead.
