### ISSUE TITLE
sample stuck

### ISSUE THREAD

**Issue by softwarevamp** [amphp/thread#15]
<?php

function slowAddition($x, $y) {
    sleep(1);
    return $x + $y;
}

try {
    $dispatcher = new Amp\Thread\Dispatcher;

```
$a = $dispatcher->call('slowAddition', 1, 5);
$b = $dispatcher->call('slowAddition', 10, 10);
$c = $dispatcher->call('slowAddition', 11, 31);

// Combine these three promises into a single promise that
// resolves when all of the individual operations complete
$comboPromise = Amp\all([$a, $b, $c]);

// Our three calls will complete in one second instead of
// three because they all run at the same time
list($a, $b, $c) = $comboPromise->wait();
var_dump($a, $b, $c);

/*
int(6)
int(20)
int(42)
*/
```

} catch (Exception $e) {
    printf("Something went wrong:\n\n%s\n", $e->getMessage());
}

not returns 
![screenshot 2015-08-08 04 52 19](https://cloud.githubusercontent.com/assets/746953/9150335/50fab3e4-3d89-11e5-8e22-66f41cd6d68e.png)

**Comment by softwarevamp** [comment]
i am using
1. Windows 10
2. php-5.5.28-Win32-VC11-x64

**Comment by rdlowrey** [comment]
Hi! This project has been neglected for a few months while we stabilized and finalized the underlying amp libs. It doesn't surprise me that things are a bit broken at the moment.

Now that we have a stable version for the base event loop library I'm planning to rewrite `amp/thread` in the next few days to accommodate the changes. I will keep you updated here.

**Comment by pieterjvrensburg** [comment]
Hi.

Any update on this? Just pulled 0.8.1 and this still happens.

Seems that the worker does not get started when the start() method is called on the newly created Thread object in Dispatcher::spawnWorker.

Any suggestions on what I can do to get this going because I would like to use this lib.

**Comment by robertfausk** [comment]
@rdlowrey any news on rewrite of ```amp/thread```?

**Comment by bwoebi** [comment]
@robertfausk @trowski planned to introduce a new amp/concurrent library, which will obsolete this library.

**Comment by kelunik** [comment]
We have stable releases now, please use `amphp/parallel` instead.
