### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by dercoder** [amphp/thread#17]
This lib use the old version of Amp:

  Problem 1
    - Installation request for amphp/thread ^0.8.1 -> satisfiable by amphp/thread[v0.8.1].
    - amphp/thread v0.8.1 requires amphp/amp ~0.12 -> no matching package found.

**Comment by ACXgit** [comment]
Same problem here, unable to install amphp/aerys and amphp/thread together in the same project. Any possibility to see it updated soon? Thank you.

**Comment by bwoebi** [comment]
We are going to discontinue this library in favor of [amphp/parallel](https://github.com/amphp/parallel), which provides a new API based on Amp v2.

**Comment by ACXgit** [comment]
Uh, I had missed it, very interesting!
Is it already usable? I get this trying to install it via Composer:

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for amphp/parallel dev-master -> satisfiable by amphp/parallel[dev-master].
    - amphp/parallel dev-master requires amphp/amp ^2.0 -> satisfiable by amphp/amp[2.0.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by bwoebi** [comment]
Somewhat usable already, there's no release for v2 yet, you need `"minimum-stability": "dev"` for this. The API isn't stable yet, but it probably won't see massive overhauls.

**Comment by ACXgit** [comment]
My composer.json:
```
{
    "require": {
        "amphp/parallel": "dev-master"
    },
    "minimum-stability": "dev"
}
```

Result:
```
# composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - amphp/amp 2.0.x-dev requires async-interop/event-loop-implementation ^0.2 -> no matching package found.
    - amphp/parallel dev-master requires amphp/amp ^2.0 -> satisfiable by amphp/amp[2.0.x-dev].
    - Installation request for amphp/parallel dev-master -> satisfiable by amphp/parallel[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by trowski** [comment]
@ACXgit You need to install an `async-interop/event-loop-implementation`, that's what the error message is telling you. (@bwoebi something we will need to make clear in the v2 docs, as I see this being a common issue). `amphp/loop` provides this implementation. Use this `composer.json`:
```json
{
    "require": {
        "amphp/parallel": "dev-master",
        "amphp/loop": "dev-master"
    },
    "minimum-stability": "dev"
}
```

**Comment by ACXgit** [comment]
Thank you @trowski, I got it up and running.
Is it also currently possible to install and run it together with `amphp/aerys`? and if yes how?

Btw, `amphp/parallel` is a truly great idea. In my personal case it's like big the missing piece in current async PHP implementations. Thank you for developing it.

**Comment by bwoebi** [comment]
Aerys is providing an amp_v2 branch `"amphp/aerys": "dev-amp_v2"` should work for now.

**Comment by ACXgit** [comment]
It works, thank you so much. I'm going to test stuff in the next days and report any issues.

**Comment by kelunik** [comment]
We have stable releases now, please use `amphp/parallel` instead.
