### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Lewiscowles1986** [amphp/thread#19]
Is the project dead? I ask because it hasn't been updated in 2 years and PHP is now a fair bit different.

**Comment by Lewiscowles1986** [comment]
looks like last commit was a year ago https://github.com/amphp/thread/commit/8c917c4f5ff01dfc81e50f2313e77e4b5b31a064

**Comment by bwoebi** [comment]
https://github.com/amphp/thread/issues/17#issuecomment-244553146

We plan to release amp v2 in the next couple of months. And then concurrent will replace this.

**Comment by Lewiscowles1986** [comment]
Thank you for update, hope you have had / are having great weekend :+1:

**Comment by nikoskip** [comment]
@bwoebi do you recommend use `amp`directly instead of this project? I need to develop a project involving parallel workers and I was reading the docs of this project an suits me perfectly: pools, timeouts, progress update, etc.

Thanks!

**Comment by bwoebi** [comment]
At the first glance, that's what you would use amp directly for, yes; eventually in combination with amphp/parallel.
